name: Alpine Php 8.2
on:
  push:
    branches: 
    - main


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  login-GitHub:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      -
        name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
         #file: ./src/Dockerfile
         context: .
         platforms: linux/arm/v7,linux/arm64,linux/amd64
         push: true
         tags:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
         outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=expeoc alpine-e-php81
